#! /bin/bash

DOCKER_NAME="macro-micro-coles" # username in container
CONTAINER_NAME="ayugay-sber" # name of container
SRC="sber_hse_hack" # source directory (supposedly, this repo's path is /home/${USER}/${SRC})

# to get these values type "id" in shell termilal
DOCKER_USER_ID=1039 
DOCKER_GROUP_ID=1039

# rename this file to "credentials" when done